"""
Build a Tesla-compatible ZIP export.

ZIP structure (must be exact):
  README.md
  LightShow/<basename>.fseq
  LightShow/<basename>.wav  (or .mp3 if explicitly requested)
"""
import io
import zipfile
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from app.services.fseq_writer import build_fseq
from app.services.job_store import Job, job_dir


def build_zip(job: Job, audio_format: str = "wav") -> bytes:
    if audio_format not in ("wav", "mp3"):
        raise ValueError("audio_format must be 'wav' or 'mp3'.")

    timeline: dict[str, Any] = job.timeline  # type: ignore[assignment]
    fseq_bytes = build_fseq(timeline)

    master_wav_path = job_dir(job.job_id) / "master.wav"
    if not master_wav_path.exists():
        raise FileNotFoundError("master.wav not found for this job.")
    audio_bytes = master_wav_path.read_bytes()

    basename = job.basename
    readme = _build_readme(job=job, basename=basename, audio_format=audio_format)

    buf = io.BytesIO()
    with zipfile.ZipFile(buf, mode="w", compression=zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("README.md", readme)
        zf.writestr(f"LightShow/{basename}.fseq", fseq_bytes)
        zf.writestr(f"LightShow/{basename}.{audio_format}", audio_bytes)
    return buf.getvalue()


def _build_readme(job: Job, basename: str, audio_format: str) -> str:
    ts = datetime.now(tz=timezone.utc).isoformat()
    return f"""# Tesla Custom Light Show

Generated by Tesla Light Show Webapp.

## How to copy to USB

1. Format a USB drive as FAT32 or exFAT.
2. Create a folder called `LightShow` in the root of the USB drive.
3. Copy `{basename}.fseq` and `{basename}.{audio_format}` into `LightShow/`.
4. Eject the USB drive safely.
5. In your Tesla, open the music app and select USB. Navigate to **Light Show**.
6. Select the show and press **Play**.

## File structure on USB

```
LightShow/
  {basename}.fseq
  {basename}.{audio_format}
```

## Details

- Basename: `{basename}`
- Audio format: `{audio_format.upper()}`
- FSEQ version: V2 Uncompressed
- Frame interval: 20 ms
- Original file: `{job.original_filename}`
- Generated at: {ts}

## Supported models

Model S 2021+, Model 3, Model X 2021+, Model Y, Cybertruck.

> Note: This show uses cross-vehicle-safe light channels only (48 channels, lights only).
"""
